In [28]:
#Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

In [29]:
# import necessary libraries
import pandas as pd
pd.set_option('display.max_colwidth', 100)

In [30]:
df = pd.read_csv(r"C:\Users\GAURAVB\Desktop\Projects\Python\LLM Project\2_news_research_tool_project\notebooks\sample_text.csv")
df.shape

(8, 2)

In [31]:
df


text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [32]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [33]:
vectors

array([[-0.00247396,  0.03626723, -0.05290459, ..., -0.09152357,
        -0.03970001, -0.04330489],
       [-0.03357268,  0.00980517, -0.03250129, ..., -0.05165466,
         0.02245888, -0.03156181],
       [-0.01865322, -0.04051315, -0.01235386, ...,  0.00610586,
        -0.07179644,  0.02773852],
       ...,
       [-0.00066459,  0.04252128, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357662],
       [-0.03317154,  0.03252454, -0.02484838, ...,  0.0117442 ,
         0.05747125,  0.00571021],
       [-0.00166395,  0.00413827, -0.04597083, ...,  0.02008528,
         0.05656242, -0.00161596]], dtype=float32)

In [34]:
dim = vectors.shape[1]
dim

768

In [35]:
import faiss

index= faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000028F80E0D950> >

In [36]:
index.add(vectors)

In [37]:
search_query = "Lets go on Holiday"

vec = encoder.encode(search_query)
vec.shape

(768,)

In [38]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [39]:
distances, I = index.search(svec, k=2)
distances

array([[1.0843159, 1.3128644]], dtype=float32)

In [40]:
I

array([[6, 7]], dtype=int64)

In [41]:
df.loc[I[0]]

text  \
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
6   Travel  
7   Travel